from .connection_test import connection_test_router
from .start_menu import start_menu_router
from .create_campaign import create_campaign_router
from .campaign_interaction import campaign_interaction_router
from .add_admin import add_master_router
from .characters_display import characters_display_router

from .start_menu import start_menu_dialog
from .create_campaign import create_campaign_dialog
from .campaign_interaction import campaign_interaction_dialog
from .add_admin import add_master_dialog
from .characters_display import characters_display_dialog